# Generated by Django 5.1.2 on 2024-11-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='name',
        ),
    ]
