# Generated by Django 5.1.2 on 2024-11-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_trailer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='order',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='order',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.theater'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theater',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.movie'),
            preserve_default=False,
        ),
    ]
